### PR TITLE
Added Start/End point distinction

### PR DESCRIPTION
**Pull request by ollydoyle**
A tidyied up version of the one here: https://github.com/Courseplay/courseplay/pull/2165

### CODE REVIEW

**Comment by pops64** [comment]
Just leave it in English when you do place text into other translation files and put in comments to next to it. To be translated. The rest of the CP team will discuss whether or not to merge this in, Close out the one you don't want to be merged as well. Thanks

**Comment by ollydoyle** [comment]
Oh OK, I just used the google translator, and limited to the full sentences, i do find it good in those cases, but i see you point

I future then

**Comment by ollydoyle** [comment]
Ok, All the google translations are taken out with the English and a todo sign in there place now.
And the new text flag in included in each file

**Comment by pvajko** [comment]
@ollydoyle , we won't be able to pull this as it is, this would be a lot of work to properly merge it because there are too many commits and there are other commits in between them on the master branch.

Please note that in git you can add many files to one commit, it does not have to be a single file per commit. 

Ideally, these changes should be in one commit (or maybe two, one for the code and another one for the translation files)

**Pull request closed without merging**
