### PR TITLE
MP impovements

### LINKED ISSUE #5975: Drive course button does nothing v6.02.00051
Hello everyone,

I'm having a problem with courseplay, it was working previously and it only appeared with the new update (which I thank you for because it solved a lot of issues), I cannot start courses for some reason, here is a video (notice that I am clicking Drive Course but nothing happens

https://www.youtube.com/watch?v=N408pT0WxOg

Logs:
`2020-08-25 12:31 Samy joined the game
2020-08-25 12:32 	### CourseplayMultiplayer: writing 23 courses 
2020-08-25 12:32 	### CourseplayMultiplayer: writing 5 folders 
2020-08-25 12:32 	### CourseplayMultiplayer: writing 1 custom fields 
2020-08-25 12:32 ShaderId envmap_blending.cg:1
2020-08-25 12:32 ShaderId envmap_blending.cg:2
2020-08-25 12:32 ShaderId envmap_blending.cg:4
2020-08-25 12:32 ShaderId envmap_blending.cg:8
2020-08-25 12:32 ShaderId envmap_blending.cg:16
2020-08-25 12:32 ShaderId envmap_blending.cg:32
2020-08-25 12:32 data/shared/ai/trafficCollision.i3d (31.43 ms)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/Events/CourseEvent.lua:27: 'for' limit must be a number
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/Events/CourseEvent.lua:27: 'for' limit must be a number
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:33 Error: Running LUA method 'packetReceived'.
2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'pp' (a nil value)
2020-08-25 12:35 Game saved successfully.
2020-08-25 12:40 Game saved successfully.
2020-08-25 12:45 Samy left the game`

When I tried yesterday, there were also the same errors but it was 
`2020-08-25 12:33 C:/users/fsserver/My Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/signs.lua:192: attempt to index local 'vehicle' (a nil value)` if I remember correctly

Thank you very much for your dedication & your time, have a very good day

### LINKED ISSUE #6008: CP zeigt die Wegpunkte nicht mehr an
Hallo, mich habe heute den neuen CP (52) auf meinen Server Hochgeladen und musste feststellen das wenn ich im CP Menü auf das "Auge" gehe zeigt er die Strecken nicht mehr an, dafür verschwindet das Seuerungs-Kästchen und der Tacho?
Mudd ich was umstellen???

### LINKED ISSUE #6020: Probleme mit MP
Hallo, zwischen beiden Versionen funzt im MP nicht.. CP version 49 funzt der Trigger nicht aber Abfahrer fehlerfrei und bei neueste  Version 53 funzt abfahrer nicht aber Trigger funzt top.. bei SP läuft alles super nur bei MP (Server) funzt nicht.. Säen/Düngen oder Feldarbeit macht Abfahrer nicht. Ich drück abfahrer einstellen und passiert nix.. er bleibt stehn und CP macht garnix.. 

Habt ihr auch bekannte Problem?

LG Chris

### LINKED ISSUE #6026: Es Können keine Kurse mehr generiert werden
Hallo, ich habe heute Festgestellt das im 052 die neu generierten kurse nicht geladen werden können, nach einem neustart sind sie weg und wieder einen neustart später sind ca 10 stück da die alle nicht angewählt werden können. 053 ist auch nicht besser, sorry

MP dedi

### PR DESCRIPTION
**Pull request by schwiti6190**
-improved debugging channel 5
-removed waypoint index, cp.text events and
  moved them to onWriteUpdate to reduce network load
closes #6026 , closes #5975, closes  #6020, closes #6008

### CODE REVIEW

**Comment by jspring0811** [comment]
Also posted this in #5975...   When I tried testing #6025 the dedi server logs started flooding as soon as I entered the game:

Testing #6025 now... There seems to be a critical issue introduced that is flooding the dedi server logs:

Warning (script): 'streamWriteBool': Argument 1 has wrong type. Expected: Bool. Actual: Nil
......\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
=C:/Users/jspri/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua (197) : streamWriteBool
=C:/Users/jspri/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (1374) : writeUpdateStream
dataS/scripts/vehicles/SpecializationUtil.lua (30)
dataS/scripts/vehicles/Vehicle.lua (1181) : raiseEvent
dataS/scripts/network/Server.lua (178) : writeUpdateStream
dataS/scripts/BaseMission.lua (1500) : update
dataS/scripts/FSBaseMission.lua (1979) : update
dataS/scripts/missions/mission00.lua (469) : update
dataS/scripts/main.lua (1927) : update

**Comment by schwiti6190** [comment]
@jspring0811 I would appreciate if you could try it again with my small fix :)

**Comment by jspring0811** [comment]
@schwiti6190 Tested again...  status logging issue is fixed, but I still have the Drive course pp issue.  Details in the #5975 thread.

**Comment by schwiti6190** [comment]
@jspring0811 could you post a complete logfile of the server and client with debug channel 5, might help ?

**Comment by jspring0811** [comment]
@schwiti6190 Server and client logs with debug channel 5 attached.  There are some interesting errors in the client log.  I was only looking at the server log earlier today.
[server_log.txt](https://github.com/Courseplay/courseplay/files/5172487/server_log.txt)
[client_log.txt](https://github.com/Courseplay/courseplay/files/5172488/client_log.txt)

**Comment by schwiti6190** [comment]
@jspring0811 thanks for your help seems like I made a typo, this one should be fixed now.

**Comment by jspring0811** [comment]
@schwiti6190 Tested again...  Drive course is still not working.

I still see signs.lua:192: attempt to index local 'pp' (a nil value) in the server log each time I press Drive course.

Server and client logs attached
[server_log.txt](https://github.com/Courseplay/courseplay/files/5175684/server_log.txt)
[client_log.txt](https://github.com/Courseplay/courseplay/files/5175685/client_log.txt)

**Comment by schwiti6190** [comment]
@jspring0811 I did a small test on a local server and the bug seems to be gone now with the latest fix. It would be nice if you could also test it on a dedicated server :)

**Pull request merged**
