### PR TITLE
Open combine pipe when waiting to unload.

### PR DESCRIPTION
**Pull request by dlbromen**
I like this suggestion #4252 . Specifically when driving the chaser cart yourself vs using CP.  To that end, I made a simple change to put the pipe out when combines are sitting on the field waiting to unload.
I've been playing with it for a couple days and it works exactly how I want as a user.
I know there was discussion in the referenced issue about making it configurable. I can certainly work on making a HUD change to accommodate a new setting, but I thought I'd start with this. For me, I don't see a reason to make it configurable, but I am here to learn. It mimics the way the built-in Helpers work also.

### CODE REVIEW

**Comment by Tensuko** [comment]
There is a big reason to make it configurable, as there are Users out there who don't want the pipe to be always open (like me).
And it should get into Advanced Settings, as it is not an option that you will change on the fly a lot, but make a decision once in a while, so no changes to the HUD.

**Comment by dlbromen** [comment]
@Tensuko - when you say "always open", you still mean to say "always open when sitting still in the field waiting to be unloaded", right? I totally agree while moving it is out of the question. I just want to make sure you're that adamant about it in the very specific cases when sitting still which is what has been done here.

**Comment by Tensuko** [comment]
No I mean it just like this:
When Combine needs Unload, Pipe only open if trailer is near, AD waits for unload.
If you want it to open the pipe as soon as the combine waits for unload, then we need an option to lets say overwrite the other conditions and just open the pipe.

**Comment by pvaiko** [comment]
@dlbromen could you add this as a vehicle specific setting, derive a class from BooleanSetting in settings.lua, add it to the vehicle settings container in base.lua and to the VehicleSettingsPage.xml.

You'll also need to add text constants to all translate files.

**Comment by dlbromen** [comment]
I'll work on adding a setting and update this PR. Thanks.

**Comment by pvaiko** [comment]
@dlbromen we have another upcoming pull request including this change, if you haven't added that setting yet then I'd close this and merge the other one instead.

**Comment by dlbromen** [comment]
I'll push up what I have and you can decide which implementation you prefer. I hadn't pushed yet because I did not have a chance to play with it as much as I wanted.

**Comment by pvaiko** [comment]
@dlbromen the other pull request did exactly what I wanted (derive setting from BooleanSetting) so I merged that one.

Thanks for your help!

**Pull request closed without merging**
