### PR TITLE
Fix and typo translation_fr.xml

### PR DESCRIPTION
**Pull request by Anonymous-any**
Some fix and typo... again clic not CLIQUE to French translators... !!

### CODE REVIEW

**Comment by Tensuko** [comment]
Instead of removing comments, you could clean thatfile by change all those space in the start of each line to one or 2 tabulators...

**Comment by polosubtil** [comment]
Hi @Anonymous-any 
Thanks for the update, never catch the "clique" ;)
Just 3 comments:
- I left "Click to switch" as I am not sure any translation would work, I just hoped the description was enough
- Same for the debug channel as I don't think anybody would use them if they don't speak any word of english
- "Afficher la course temporaire" looked more appropriate as this is not only the turn but also the path (course) in the field to get to the combine
But I don't really mind in the end :)

**Comment by Anonymous-any** [comment]
Hi there, sure @Tensuko I will see your request and try to clean what the contributors translators are doing so...but I was not my goal !
@polosubtil I see some english so I think it's stupid to have a file for translate and not maxi use it.
If you think you can leave some few english so why do you want do it so? (my view point).
For "Click to switch" of course and lots in fact, the place is limited that why too I tried to resumed shortly and other thing who that not been showed good in the interface. So I started from the principle that we can only switch in vehicles and "Cliquer/Clic pour basculer ou changer" will be more longer and not sufficient explain to my view point it must have another arg line "basculer where ? into a vehicle man"...so it's more longer. You can do better maybe if you have it.
Same for the debug channel you can replace it as you want but I think so then it is sad translate with forgot some words. Plus everyone know clearly what debug channel do without use translated (except a retarded dunno) but it's more pleasant to be comfortable don't you think ?
For the last I do https://github.com/Courseplay/courseplay/issues/6266#issuecomment-725646893
because I was not really sure and understand why I've not see some explain of @Tensuko inside the interface "show debug line",
and maybe I was in discussion about maneuvers linked I tried to be more clear about what really want to do the function, of course it's temporally but of course too it's maneuvers not courses because it's already taken into account in other buttons of HUD for this. Again you make what you want after my push merge or not as you hear.
For your info I like my native language, and I'm a patriot !

Br

**Comment by Anonymous-any** [comment]
I have wrong somewhere you laugh @polosubtil ?

**Comment by polosubtil** [comment]
Just the conclusion

**Comment by pvaiko** [comment]
@polosubtil it is your call if this pull request can be merged or not (I don't speak French and you have been maintaining the French translation for quite a while now)

**Comment by polosubtil** [comment]
@pvaiko,
Yes you can merge, no problem for me except the few points I raised but they are not major. Most of it is actually quite good, as I never took the time to tidy things up. We'll see if we need to change them again in the future

**Comment by Anonymous-any** [comment]
Salut @polosubtil ok j'ai bien compris qu'en fait c'est vous qui avez bloqué la situation sans même m'en parler je trouve sa ridicule, puisque j'ai hakusé à tord @Tensuko ...https://github.com/Courseplay/courseplay/pull/6315#issuecomment-726776387

Qu'il en soit ainsi, je doit ajouter et je ne ferai pas le suivant qu'il me restait, une autre modif à faire à que je vous concède :
258 		<text name="COURSEPLAY_MODESPECIFIC_SETTINGS"						text="Paramètres de mode" /> où mod n'est pas un MOD mais un mode !! visiblement.
Pour le coup je trouve un peut honteux aussi pardonnez moi pour le pied de nez, que vous placiez des "Majuscules" en milieux de texte parfois, je ne suis pas étonné alors que les traduction sont à réexaminer par ailleurs.

Aller bonne réception polo pas si subtile :)

**Comment by polosubtil** [comment]
Bonjour @Anonymous-any 
Non je n'ai rien bloqué du tout, j'ai juste donné mon avis plus haut car on me l'a demandé, gentiment, calmement... Rien de personnel.
Comme je fais des traductions de temps en temps, pvaiko m'a demandé mon avis, rien de plus...
Mon dernier commentaire disait que la grande majorité des modifications apportées étaient très bien, que j'avais simplement remonté 3 points mais qui n'étaient pas très important, j'ai donc donné mon accord (même s'il ne compte absolument pas, je ne fais pas partie de l'équipe du tout) et les modifications ont été validées.
Pour info, je n'ai pas tout traduit, j'ai surtout géré les nouvelles traductions et modifié quelques bricoles ici et là.
Pour les majuscules, merci de l'avoir fait car c'était là dès le départ et je n'ai jamais pris le temps de le faire.

Bref, merci pour le coup de main

**Pull request merged**
