### PR TITLE
Minor fixes & Tweaks

### PR DESCRIPTION
**Pull request by Lillemats90**
**Raised modDesc descVersion to 47**
-47 is current modHub version
**Added new English Description**
-Also Translations for this to many of the languages
**Created new mod Icon that fits Giants Description**
-(it has not been added in iconFilename(modDesc) in case you don't want to 
use it)
**Cleaned up the modDesc a little**
**Scaled Store.dds to FS19 standards**
-512x512
**Added all missing game languages, Some translations might be a bit rough.**
-list of languages next to Title
**Added Credits section to modDesc**

### CODE REVIEW

**Comment by Lillemats90** [comment]
yes that is true.
anytime, happy to help out, the english translation where a bit wierd so figured it would come in handy with a new one.
yeah we did some translations by hand, for those languages we know, and used translate for the rest. 
and know how bad that might end up sometimes, but thats where we where hoping you the creators & the community could help out making those translations right :)
i can ofc just put those that had a description back to how they where, and let someone else handle updating those.

**Comment by Lillemats90** [comment]
We have changed some stuff back, also some translations might be a bit wierd still but hopefully you can get some help fixing those.

*Spelling Errors + Translations*
***Translations-Translators***
reverted some translations back to original

**Comment by pvaiko** [comment]
@Lillemats90 I absolutely like the new English text but agree with @pseikoNL, the Google translations are full of confusing mistakes and grammatical errors. 

I think no translation or English is better than a bad translation. What are the languages you know, I'd like to keep those only.

**Comment by Lillemats90** [comment]
Yes I agree with that, I'll remove them when I get home later and push it again. Don't want it to be to confusing. I know italian, and some Spanish. But my own Spanish translations might be almost as bad as Google. Also we have one here that knows the traditional Chinese. But I'll give it a look later today 😉

**Comment by Lillemats90** [comment]
**All Google translations have been removed.**
I've translated the Spanish & the Italian to the best of my abilities, they should be close to grammatically correct now.

**changes:**
***removed google translate***
***updated version number***
reverted the rest of the translations back to original

**Comment by Nickem112** [comment]
is coureseplay does not put the pip out the haverster is it fix on mp

**Pull request merged**
