### PR TITLE
Update translation_br.xml

### PR DESCRIPTION
**Pull request by rogeriodec**

### CODE REVIEW

**Comment by pvaiko** [comment]
Please coordinate with our long time translator @Admilson before creating pull requests.

**Comment by rogeriodec** [comment]
I just wanted to collaborate. Nevermind...

**Comment by Admilson** [comment]
complies with the Portuguese language rule.

**Comment by rogeriodec** [comment]
@Admilson qual o motivo de não aceitar minha colaboração?

**Pull request closed without merging**
