### PR TITLE
Display full vehicle name

### PR DESCRIPTION
**Pull request by KITT3000**

### CODE REVIEW

**Comment by Tensuko** [comment]
There is an Error:
2021-08-29 13:41 Error: Running LUA method 'loadTriggerCallback'.
2021-08-29 13:41 I:/Dokumente/My Games/FarmingSimulator2019/mods/courseplay/helpers.lua:45: attempt to index local 'vehicle' (a nil value)

**Comment by KITT3000** [comment]
In what situation does this arise? I checked vehicles mainly on field work and everything worked fine.

**Comment by Tensuko** [comment]
When enter triggers, in my case on an unload course when unload into a BGA with Mode6.

**Comment by Tensuko** [comment]
I need to correct it, it didn't happen on enter trigger now.
I have to watch the driver more, give me a few min...

**Comment by Tensuko** [comment]
Ok it is trigger but this one:
fsScreen_2021_08_29_14_21_53

fsScreen_2021_08_29_14_22_02

I rly have no Idea why that happens...

**Comment by KITT3000** [comment]
Maybe this fix will help, it should now check for `vehicle` and abort execution of the rest of the code when it is `nil`

**Comment by Tensuko** [comment]
That fixed the LUA Error.

**Pull request merged**
