### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by Simba76**
Translation Chinese

### CODE REVIEW

**Comment by Simba76** [comment]
Translation Chinese

**Comment by gui7545** [comment]
ToolTips: Each time you want to do a translation, just press the edit button on this page: https://github.com/Courseplay/courseplay/blob/master/translations/translation_cs.xml
capture
The pull request will be must clear

**Comment by JakobTischler** [comment]
@Simba76: please proceed as Gui7545 has described. That makes it much cleaner for us.

**Comment by JakobTischler** [comment]
Simba, as I've asked you before, please stop merging our changes into your pull request. Only edit your translation file, as Gui7545 has described - that's all.

**Comment by Simba76** [comment]
I'm sorry
I see it now

**Pull request closed without merging**
