### PR TITLE
Fixed AutoDrive course loading bug and other course editor issues. 

### PR DESCRIPTION
**Pull request by russbeuker**
COURSE EDITOR CHANGES
  1) A save attempt is no longer carried out when using the save hotkey on an unsaved course.
  2) You can no longer launch the editor on an autodrive course.
  3) Fixed 'unable to load autodrive course' error. #4760
  4) For best course loading performance, set the hud to not load courses at startup, especially if you have a lot of large courses.
  5) If you load a saved course and it looks like it has the wrong edits, then clear the course and click the reload courses button, then load the course again.
  6) Now when generated courses that have a zero speed show the speed as 'auto' in the waypoint info panel.  This tells you that courseplay will calculate the speed for that waypoint.  If you change the speed with the hotkeys, it will show the actual speed.  Reduce the speed to zero again and it will show 'auto'.
  7) Now dragging is done with the courseplay primary mouse button, instead of always button 1 which is the left mouse button.  If you change the courseplay primary mouse button mapping, you will need to restart the game for the changes to take effect.

### CODE REVIEW

**Comment by betrox007** [comment]
Realy nice thank's Russ..

**Comment by pvaiko** [comment]
@russbeuker just confirming you received my email.

**Comment by russbeuker** [comment]
Hi Peter,

Many thanks for the reminder and I had received your two emails and then promptly forgot to reply.  I do appreciate your dev tips and I have been trying them out, along with IntelliJ and EmmyLua.  I joined the discord channel as well.  I have some questions/observations:

1) I had a question on how to add/propose new features.  For example, I have added on my local copy of Courseplay an option to enable switching to a vehicle in the viewport when you click on it.  I find it to be much faster than tabbing and now I tab a lot less if the vehicle is already in view.  Should I create an issue with this proposal, or just do a pull request for review?  Not sure if this belongs in Courseplay since it isn’t course-related, but it is handy.  It’s less than 50 lines of code.  Please let me know what to do.
2) To test the new CombineUnloadAIDriver, do I need to use the CombineUnloadAIDriver branch, or can I activate it in the main branch?  I do pretty well all grain farming with the current mode 2.

Cheers,

Russ Beuker

**Comment by pvaiko** [comment]
Just do a pull request.

And yes, you need to check out the CombineUnloadAIDriver branch for the new Mode2

**Pull request merged**
