### PR TITLE
Update Settings and removed runCounterActive button 

### PR DESCRIPTION
**Pull request by schwiti6190**
--runCounterActive integrated in to RunCounterMaxSetting as "disabled"

-StopAtEndSetting
-AutomaticCoverHandlingSetting
-AutomaticUnloadingOnFieldSetting
-DriverPriorityUseFillLevelSetting
-RunCounterMaxSetting
-UseRecordingSpeedSetting
-WarningLightsModeSetting
-ShowMapHotspotSetting
-SaveFuelOptionSetting
-AllwaysSearchFuelSetting
-RealisticDrivingSetting

### CODE REVIEW

**Comment by ddewar** [comment]
As a new Lua user here I'm going to throw in a few suggestions. I'm not sure how easy it is in Lua, but these are usually the types of things I look out for in my Ruby and C# PRs. 

1. Lines calling `:is(true)` i.e. ( `self.vehicle.cp.settings.stopAtEnd:is(true)` ) are begging for some sort of boolean returning method to simplify your call. In Ruby we would usually do something like `function self.stopAtEnd?()` (but I don't think you can use ? in function names in Lua). But ideally, a method that returns true/false instead of calling the settings directly. The call would be a lot easier to use as `self.vehicle.cp.settings.isStopAtEnd()`

2. Some of these calls are getting very verbose with the addition of another class in the name. For example `self.vehicle.cp.settings.useRealisticDriving:is(true) `. I am wondering if there's anything we can do to reduce the [Demeter violations](https://medium.com/better-programming/demeters-law-don-t-talk-to-strangers-87bb4af11694) we are experiencing. I'm not a stickler for Demeter's Law, but it might be helpful to help restructure some things like this. Some helper methods, or having the cp class delegate the calls to the settings class might help reduce some of the complexity. [Here](https://stackoverflow.com/questions/14919282/call-delegation-in-lua) is an example of a way to do delegation in Lua I ran into this morning. I know this is a slippery slope, but settings might be a nice point to sneak in some early OO principles.

Ideally, with some changes like this, we could end up with some cleaner calls like: 
`self.vehicle.cp.settings.useRealisticDriving:is(true)` -> `self.vehicle.cp.isUseRealisticDriving()`
`self.vehicle.cp.settings.stopAtEnd:is(true)` -> `self.vehicle.cp.isStopAtEnd()`

Just some suggestions for the team to think about. I know we are trying to make an OO push, and this could help clean up some complexity. Just some things to think about @schwiti6190 and @pvaiko. If needed, I am happy to help follow up with some commits after this is pushed out to test some of these ideas.

**Comment by pvaiko** [comment]
> Just some suggestions for the team to think about.

Well, until recently there wasn't really a team around (at least a team of developers) which of course limited the refactoring efforts to a minimum. CP has accumulated an enormous amount of technical debt through its long history.

For 1: I agree, the :is() was just a generic comparison for the Setting class (which is where the BooleanSetting derived), I don't like it either, you are more than welcome to improve it.

For 2, I'm not so sure, in case of the settings I'd just probably pass them in to the AIDriver constructor directly instead of through the vehicle, as cp isn't really a class it is just a huge flat table everything CP related thrown into it.

**Comment by schwiti6190** [comment]
@pvaiko I've tested the mode1 completly as I've restructed it a bit, the rest I've tested for bugs until no more log errors occured and if the "buttons" work, but not everyone for ingame functionality.

@ddewar I have to say, your points seems like a good way to improve a bit off code, sadly I have to say that most off my programming knowledge is self taught, so my horizon is limited in concepts like OO. Maybe we could get right off the .cp. one for all the settings longterm and work only with direct call like self.vehicle.settings.StopAtEnd:get() instead of self.vehicle.cp.settings.stopAtEnd:is(true). Might be problematic as vehicle is a global ingame vehicle variable, if I am correct and might cause mod problems not sure, though.

**Comment by ddewar** [comment]
If it's okay with you both @pvaiko and @schwiti6190, I would like to take a pass at enhancing with the points I brought up now that this is in master.

**Comment by pvaiko** [comment]
@ddewar absolutely, thanks.

**Pull request merged**
