### PR TITLE
Land with 8 rows

### PR DESCRIPTION
**Pull request by polosubtil**
Just a suggestion. I am working with standard equipment and 6 rows are not enough, especially with a 6m corn header. I just increased the number to 8 rows and change one of the options for 5 rows as I think it was wrong but can't be 100% sure.
Ideally, but I have no idea how to do it, the number of rows in Land depends on the work width:
- up to 8 meters => 8 or 10 rows
- after 8 meters => 6 rows
Or is set manually in the course generator (again, no idea how to do that)
If this is crap, just delete it ;)

### CODE REVIEW

**Comment by polosubtil** [comment]
Thanks @pvaiko, and sorry about the mess with my branch, but I still struggle with Github ;)
Do you want me to start again or is it fine like that ? As I said, I don't have the skills to do the settings for it

**Comment by pvaiko** [comment]
No, it's fine now. Try next time.

**Comment by polosubtil** [comment]
Ok perfect.
Do you want me to increase the max number of rows in Land if you are going to do the setting part ? Should we allow up to 20 or something like that for pull harvesters (potatoes and sugar beets) ? Or more ? Or less

**Comment by pvaiko** [comment]
Oh, that would be great, I'd make it a manual setting in the course gen window (maybe preset to something based on the width). 20 seems to be a lot of work to me, maybe up to 12?

**Comment by polosubtil** [comment]
12 it is then !!! I will do that tonight and do a proper PR later. Can you push that PR anyway so we can have 8 rows in the next version while we wait for the setting part ? Or not ? :)

**Comment by pvaiko** [comment]
I'd like to push it after I added it to the course gen screen.

**Comment by polosubtil** [comment]
@pvaiko, I guess I am far from good as I can't find a way to reset my fork. I just spent 2 hours on youtube trying to understand but I think I miss basics ;)

**Comment by pvaiko** [comment]
@polosubtil don't worry about it, it's isn't nice but we can handle it.

**Comment by polosubtil** [comment]
@pvaiko 
I did a new PR with 12 rows

**Comment by Goof245** [comment]
This might be of use: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Pull request closed without merging**
