### PR TITLE
closes #5991 and trigger speed problems

### LINKED ISSUE #5991: mode 1 loading water doesnt work anymore.
mode 1 the driver doesn't stop to load water from the water tower. only if I press the loading key manually it stops and loads.
then it drives to my liquid silo it unloads but when it's empty he doesn't drive away again.
[log.txt](https://github.com/Courseplay/courseplay/files/5135986/log.txt)

### PR DESCRIPTION
**Pull request by schwiti6190**

### CODE REVIEW

**Comment by candymant** [comment]
hey, I tested the changes if I now start the course then the driver stops at the water tower load water, and drive to the unloading point. when he is at the unloading point course play stops and trow a Lua call stack.
here is the log file.
[log.txt](https://github.com/Courseplay/courseplay/files/5152539/log.txt)

**Comment by Tensuko** [comment]
And what Trailer ?
Those Water Trailers are not working for unloading right now, that we know already.
What Trailers should work are liquid manure Trailers.

**Comment by candymant** [comment]
water trailers an in-game one and a mod trailer from missy B.

**Comment by Tensuko** [comment]
Just wait for the release

**Comment by Dmitriy-30** [comment]
Комбайн не едит и останавливается курс отключается

**Pull request merged**
