### PR TITLE
div. translation changes

### PR DESCRIPTION
**Pull request by polosubtil**
- French translation update
- changed translation mode 8 from "COURSEPLAY_DRIVE_ON_AT" to "COURSEPLAY_MOVE_ON_AT"

### CODE REVIEW

**Comment by Tensuko** [comment]
That is not a typo, but it might make more sence, as this is an empty process like Mode3 Overloader.
Did you try it out then ?

**Comment by polosubtil** [comment]
I did try but I didn't get the chance to make it work for some time to make sure. I think this really needs to be looked at by @schwiti6190 or @pvaiko.

**Comment by schwiti6190** [comment]
@polosubtil what exactly is the problem with your changes, as your current changes should just swap the variables and doesn't change the functionality, as it was before ?

**Comment by polosubtil** [comment]
@schwiti6190, I was just trying to use that variable (lower than X) as it was using the other one (higher than) and it was really confusing for the translation for me :)
As I am not a dev, I am not really sure what I am doing, I tried that and it looked fine, but I don't want to brake internet or to set any computer on fire because I messed up the code ;)
So I just wanted to look at my changes and see if it makes sense to you, if something is missing or incorrect

**Comment by schwiti6190** [comment]
```
<text name="COURSEPLAY_DRIVE_ON_AT" 		text="Drive on at:" />
<text name="COURSEPLAY_MOVE_ON_AT" 		text="Drive on at less then:" />
```
@polosubtil it depends on which of these two you are trying to use for mode 8 ? the top one is currently used and in your PR you've changed it to the second translation.

**Comment by polosubtil** [comment]
Yes, that’s what I am trying to do : the driver will go for a refill when under a certain fill level

**Comment by Tensuko** [comment]
It is baiscally just a more clear definition in the text, of when he drives on to refill himself.
Not a bad idea, rather then start drive off when he reached a value (like Mode2 driver when reach 90% they drive to unload).

**Comment by schwiti6190** [comment]
@polosubtil If the functionality of Mode 8 is still there, then we could merge this unless you've planned something more or different :)

**Comment by polosubtil** [comment]
Hi @schwiti6190,
From my tests, sounds like functionality for mode8 is still there, only the text is easier to understand. For me it's fine like that, if you approve my changes on the technical side you can merge
Thanks for your help, and sorry for the confusion ;)

**Comment by schwiti6190** [comment]
@polosubtilI I would have to thank you for this PR, as this project basically depends on the help of the community :)

**Comment by polosubtil** [comment]
My pleasure, great work guys ;)

**Pull request merged**
