### PR TITLE
Update hud.lua

### PR DESCRIPTION
**Pull request by ollydoyle**
courseplay-ollydoyle-Start-End-Distinction-1

for https://github.com/Courseplay/courseplay/issues/2161

### CODE REVIEW

**Comment by ollydoyle** [comment]
I added the page to the list of constantly refreshed ones.

and a check of the state of headland -land sequence were is changes the text based on the there order.

i couldn't understand the text string format used, so i left in the old stuff, commented out, and redid the text strings as best i could.

some text is hard coded in English which would need to be moved to the translation but i figured i would do one at a time

**Comment by pvajko** [comment]
@ollydoyle thanks for the change, not sure what your plan is, are you going to put everything into the translation? I think the easiest would be to just have a COURSEPLAY_CORNER_5_START/END etc.

**Comment by ollydoyle** [comment]
well i was going with a standalone flag with the "start at" "end at", which could be used elsewhere for something in the future.
also i don't know how to format the string well enough too have  COURSEPLAY_CORNER_5_START/END 
because i see in some of the code in different file i seem to call these thing using just the number part. or maybe I'm wrong. I just don't want to mess anything up.

but i think this is good enough to use write now, cause it takes me so  long to do this. it was like 7 hours to figure out this much

**Comment by ollydoyle** [comment]
Ok after looking again i just did what you said.
also the way i was think might mess with sentence structure in other languages

**Comment by pops64** [comment]
Just leave it in English when you do place text into other translation files and put in comments to next to it. To be translated. The rest of the CP team will discuss whether or not to merge this in,

**Pull request closed without merging**
