### PR TITLE
Update hud.lua

### PR DESCRIPTION
**Pull request by Innallas**
-- add condition for the hud opening shortcut selection to work

### CODE REVIEW

**Comment by ThomasGaertner** [comment]
whats the difference in function here ?

**Comment by Innallas** [comment]
Erf its not working sometimes even with this :/ very weird, this one make it sure to assign variable , why a true or false var + and condition + key assigned, are we sure it will make like a if statement / ternary ?? (i start coding in lua script so im not sure for this)

**Comment by Innallas** [comment]
in fact i really think that script dont understand this "ternary" because in another mod i have a function ternary that someone created to use.

I put it with :

function hm:ternary(cond, T, F)
    if cond then return T else return F end
end

**Comment by pvaiko** [comment]
The standard way in lua for a ternary is x = a and b or c which you could have found in 30 seconds googling it instead of writing a function.

**Pull request closed without merging**
