### PR TITLE
Add AD vehicle support

### PR DESCRIPTION
**Pull request by Axel32019**
Support AutoDrive in Leveling and compacting mode

### CODE REVIEW

**Comment by pvaiko** [comment]
Something is not right with this pull request, the entire file shows up as new and there is a conflict. This can't be right.

Also, a bit more details on what exactly the change does would be great.

**Comment by Axel32019** [comment]
@pvaiko Hi Peter,
I don't know why the file is shown as new, I took it from master and added the following as mentioned in #5662:
if courseplayer ~= nil and courseplayer.spec_autodrive and courseplayer.spec_autodrive.HoldDriving then
courseplayer.spec_autodrive:HoldDriving(courseplayer)
end
This will stop an AD vehicle in the search range of the compacter. 
As long as the compacter is calling the function courseplayer.spec_autodrive:HoldDriving(courseplayer) the AD vehicle will stop and remain at the postion as per my understanding. When the compacter reaches the park position it will no longer call this function.
After a timeout of  3 sec the AD vehicle will continue to drive and unload - implemented in AD.
When the AD vehicle leave the search range of the compacter it will continue it's work.
I hope this is understandable.
Me and a colleague just tested the interaction and it works as expected.

**Comment by pvaiko** [comment]
Thanks, that's great. Would you be able to create a correct pull request where those added line show up as such, and there really shouldn't be any conflicts.

**Comment by Axel32019** [comment]
Can you give me a hint how to get the fork updated with git on Windows?
This is too strange for me...

**Comment by pvaiko** [comment]
lmgtfy: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

**Pull request closed without merging**
