### PR TITLE
Update FieldworkAIDriver.lua

### PR DESCRIPTION
**Pull request by jobyrns72**
Allows for attached combines with detachable cutter and pickups to be recognized by courseplay as a combine

### CODE REVIEW

**Comment by Tensuko** [comment]
We still don't know what Combine you are talking about...

**Comment by TinyCrocodile** [comment]
@jobyrns72  just post a screenshot of the mod so @Tensuko can see how it looks like.

**Comment by Tensuko** [comment]
Link to the mod would be even better (or what vanilla Tool it is) and also what exactly did not work,
Combines are normaly NOT handeled in the fieldWorkerAiDriver.lua Thats why we got a CombineAiDriver.lua

**Comment by jobyrns72** [comment]
http://www.farmingsimulator19mods.com/new-holland-fp240-v1-0-fs19/ 
I'm fairly aware of how it works but we are working with an implement as was stated. As in the code shows you have the validation of cutter and pickup to be recognized. This just makes it one step easier and makes this mod work and whatever ones in the future

**Comment by pvaiko** [comment]
@jobyrns72 I was going to check that mod but that website is a big pile of adware and malware with five million download buttons and I'm too old to find the one actually downloading the mod and not installing some shady browser extensions :)

But in general, if you look at the Giants code (https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=318#getCanImplementBeUsedForAI3414) the main reason an implement can't be used is that it has no AI markers. So I'd prefer checking that first and I believe the cleanest way to fix this is to add those AI markers to this implement. I don't really like the idea of force-enabling everything with a Combine spec for Courseplay as it could lead to all kinds of issues with other implements.

**Comment by jobyrns72** [comment]
Well that was my next thing I'm working on is fixing that but still wouldn't be able to work bc the cutter and header are separate attachments. Your pick up headers are a problem not matter what. The base implement is set up as a base fillable

**Comment by jobyrns72** [comment]
https://www.yesmods.com/fs19-mods/harvesters/forage-harvesters/new-holland-900-chopper-am/
 This is a good sight

**Comment by pvaiko** [comment]
I made the pickup headers work recently in c4b3c607453b30b98726c2e532d65659e47242ed.

What _exactly_ is the problem with this implement and does adding Combine here solve all those problems?

**Comment by pvaiko** [comment]
> https://www.yesmods.com/fs19-mods/harvesters/forage-harvesters/new-holland-900-chopper-am/
> This is a good site

Sorry, but same crap as the other.

**Comment by jobyrns72** [comment]
The problem is without the work around courseplay is not giving it call driver page in work mode. The thing I did was after looking at the pottinger mex 6 i change in the moddesc the parent class to attachedCombine which fixed the call driver page but caused other problems bc the base implement itself has no cutter or pickup area. I then put it back to original and we found that work around and everything works as it should. The only thing I noticed that at the start you have to swap between field work mode then to just drive mode back to field work mode for the call page to light up

**Comment by jobyrns72** [comment]
I'll upload a copy tonight if need be seen like all of them are sharemods files

**Comment by pvaiko** [comment]
You can try use getImplementWithSpecialization() here (without the AI): https://github.com/Courseplay/courseplay/blob/caea0f82e6c1ce476ed1e5784a85047185e4fb94/CombineAIDriver.lua#L76

**Comment by jobyrns72** [comment]
Hmm so pretty much doing the same thing without messing up ai implement

**Comment by jobyrns72** [comment]
Ok got it working with your suggestion but that was 1/3 of it. Line 119 CombineAiDriver had to changed to just implement and line 60 of UnloadableFieldworkAiDriver had to be change to just implement too. I'm on my phone at work so don't think I can change anything on the app lol

**Pull request closed without merging**
