### PR TITLE
Update TrafficCollision.lua

### PR DESCRIPTION
**Pull request by Innallas**
Check and set "dt" to avoid errors in loops and slow down behind car

### CODE REVIEW

**Comment by ThomasGaertner** [comment]
in which condition should dt be nil ?

**Comment by Innallas** [comment]
It always happen when the vehicle arrive behind another one > then errors in loops and vehicle keep accellerate

**Comment by ThomasGaertner** [comment]
do you have a log of these errors ?

**Comment by Innallas** [comment]
Not anymore because i dont have it anymore but i will remove the test tomorrow to show you

**Pull request closed without merging**
