### PR TITLE
Update CombineAIDriver.lua

### PR DESCRIPTION
**Pull request by jobyrns72**
2nd part

### CODE REVIEW

**Comment by jobyrns72** [comment]
Sorry this my first time doing these. Dont know how to do multiple edits at once

**Comment by Tensuko** [comment]
Always give more Information about what is not working, we don't simply add any Code just becouse on random vehicle suddenly works, as you saw in other PR, there are sure more proper ways, but we HAVE to know what is NOT working 1st.

**Comment by pvaiko** [comment]
> Sorry this my first time doing these. Dont know how to do multiple edits at once

You have now three pull requests open. We need one pull request with all the changes in that single PR, with a short explanation about what the problem was and how it is now solved.

Thanks.

**Comment by jobyrns72** [comment]
Sorry like I said I'm still learning how to use this. Didnt mean to send this out

**Comment by pvaiko** [comment]
closing due to inactivity.

**Pull request closed without merging**
