### PR TITLE
Updates for #3393

### PR DESCRIPTION
**Pull request by cyberndj**
Updates for issue #3393  Allowed all workers on "Seed and Fertilize" and "Fieldwork" mode to utilize "Combine Convoy" mode in the HUD. Also edited the EN translation file to have text display capitalization and/or camel case.

### CODE REVIEW

**Comment by pvaiko** [comment]
Thanks. Next time please don't change things not related to the subject of the pull request.

**Comment by pvaiko** [comment]
@cyberndj looks like this broke the fertilizer function #3443 ?

**Comment by cyberndj** [comment]
Bummer, didn't intend to break other things. Can you roll this back or do you need me to do a new pull request reverting the changes?

**Comment by pvaiko** [comment]
Sure, I can revert it but would prefer to have it fixed it so we have both...

**Pull request merged**
