### PR TITLE
Add button for reload course list.

### PR DESCRIPTION
**Pull request by FillPavS**
Hi. When I plot a course, I sometimes make mistakes and the tractor rests on the haystack or other obstacles. In order not to re-route the route, I use the program for editing the course (yCourse17). When I edited the course and in order for the changes to take effect, I have to go to the main menu and load the save. I added a button to update the list of courses and now you can not go to the main menu. Sorry for my english :)

fsscreen_2017_04_26_19_58_55

### CODE REVIEW

**Comment by pvajko** [comment]
This is a great addition for those who use an external course editor like yCourse17 or [my course generator](https://github.com/pvajko/course-generator). I just tested it and was able to generate and load a course without restarting the game.

**Comment by gec100** [comment]
This would really be a great simple addition to CP. Can we expect it to be implemented?

**Comment by pvajko** [comment]
You can use FillPavS' fork (https://github.com/FillPavS/courseplay) until they merge this change.

**Comment by Satissis** [comment]
One thing I would like you to do before I merge this in, is goto each language files that you have not translated and put in the english translation line in each of them, so all the other translators know that they need to translate that line.
I normally also add:  at the end of the new line in each untranslated file, for easier search.

**Comment by Satissis** [comment]
Oh and @FillPavS 
Jakob is not developing CP anymore, if you didn't know ;)

**Comment by FillPavS** [comment]
@Satissis, I added a line with each translation file. I hope that I did everything right and did not break anything :)

**Comment by Satissis** [comment]
Alright looks fine now :)
I'll merge

**Comment by andreasthu** [comment]
```
Error: Running LUA method 'loadMapFinished'.
C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua:42: attempt to index field 'signs' (a nil value)
Error: Running LUA method 'MultiOverlayV2.timerUpdate'.
C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/MultiOverlayV2/scripte/moSetGetStationes.lua:170: attempt to index field 'economyManager' (a nil value)
Application exit request forced.
Application exit request forced.
```
have i now with this version
lg
andreas

**Comment by FillPavS** [comment]
@andreasthu Sorry if I broke something :) Can you use this assembly and describe the result? I think I know where there can be a problem, but I do not know how to fix it yet :( button until will not disappear with a loaded course.

[ZZZ_courseplay.zip](https://github.com/Courseplay/courseplay/files/983344/ZZZ_courseplay.zip)

**Comment by andreasthu** [comment]
hello
no, you broke nothing :-)
i delete this zip and copyed the 0133 backup zip in the mods-folder
with the normal 0133 courseplay the game runs fine  and without the Errors in the log.
i will try your attached zip later this day
lg
andreas

**Comment by andreasthu** [comment]
ok thanks.
game starts without this errors.
bevore i install your zip, i start ls17 normal and fired al cp helpers and cancel all courses in the tractors.
then i end the game, place your zip in the folder and start ls17 again.
now it works.
i can start courses and all.
i will  try  to relaod courses next day

lg
andreas

**Comment by FillPavS** [comment]
@andreasthu OK. I understood where I made a mistake. I'm not sure that I solved it correctly, but it's worth trying what I corrected. Try it
[ZZZ_courseplay.zip](https://github.com/Courseplay/courseplay/files/984921/ZZZ_courseplay.zip)

**Comment by andreasthu** [comment]
Same errors.
Cant load a savegame

**Comment by FillPavS** [comment]
@andreasthu it should work;)
[ZZZ_courseplay.zip](https://github.com/Courseplay/courseplay/files/986478/ZZZ_courseplay.zip)

**Comment by andreasthu** [comment]
thanks,
 i will test it in the evening,
lg
andreas

**Comment by andreasthu** [comment]
works now fine, thanks
lg
andreas

**Comment by sootysax** [comment]
this should have gotten it's own version # - i totally missed this and had a release .133 without the button

**Comment by pops64** [comment]
@andreasthu if you having issues with this please post a full log in the issues section.

**Comment by andreasthu** [comment]
ok i will to
sry, for maybe misunderstanding
my english is not the best.
sometime i understand only half or  Interpret some things false.
thought this was the "official post" for this Thema
lg
andreas

**Comment by pops64** [comment]
This was the post for merging in this suggestion. If you have an issue we would prefer it to be in the issues section which is a little more accessible to all.

**Pull request merged**
