### PR TITLE
Reload button function fix

### PR DESCRIPTION
**Pull request by FillPavS**
A separate function for the reset button. That there were no conflicts.

### CODE REVIEW

**Comment by FillPavS** [comment]
Do not merge please. I removed the extra lines in the function. I'll check in the evening and place if everything is fine. Thx ;)

**Comment by FillPavS** [comment]
Because I'm not good at programming ;) and this is the way I managed to solve the problem. If you can solve it in an easier way, I will be very grateful to you.
In pull request #2016 the andreasthu game was not loaded. The error was in the line where I indicated to hide the button when the route was loaded.
` 				if fn == "reloadCoursesFromXML" then
					show = g_server ~= nil and not vehicle.cp.canDrive;`

**Comment by pops64** [comment]
:P you comment the same time I edited mine. the function you call has no purpose until you implemented your change has far as I can tell.

**Comment by FillPavS** [comment]
With these changes, the andreshu game is loaded. It also loads if I stop hiding the button. So somewhere this function is used I think.

**Comment by pops64** [comment]
I asked him for a full log cause my guess is there is something occurring earlier on that is causing this. Because on game load there are parts of this function that are called which is why the courses are loaded. My guess is this function got put into place but never got implemented or it was implemented in FS15 but was removed in the 17 conversion. I did a find through every file of cp for that function and I can find no place where it is called. If you want you can remove the and not vechile.cp.canDrive has inside of its function is a safeguard to prevent reloading the currently loaded course.

**Comment by FillPavS** [comment]
I hide the button because it's in place of the delete route button. I no longer found a place in the interface where to place it.
Sorry if I do not understand everything you write. In most I write through an interpreter and read too;)

**Comment by FillPavS** [comment]
I removed the extra in the function. Now when the course list is refresh, the camera does not move and there is no small freezing.

**Comment by pops64** [comment]
That looks a lot better. But my guess is there is something else going on. May be because the delete button and reload button are on top of each other. Maybe try hiding the delete button if you are showing the reload button instead of making a new function.

**Comment by FillPavS** [comment]
@pops64 Did you run my build? The delete button was hidden when the route was not loaded. Of course, two buttons are not displayed simultaneously. Or you have on another? 
When I cleaned the excess friezes disappeared.

**Comment by andreasthu** [comment]
@pops64
@FillPavS
First let me say that i find it fantastic what you all make with courseplay. I find one of the best and must have mods for ls17.
I am sorry about that i am the point of our dispute.
Its right my ls17 wont load with the stock co v 010133 and FillPavS make some versions, i think 5 or 6 until cp works again with my ls17.
Thank you.
I also played ls17 now with cp 010136 and 010137 (010138 not testet yet, maybe tonight) and with this two versions i was able to play ls17 fine.
Thanks pops64.
You both and all others make good jobs and i hope in future also.
Greets
Andreas

**Comment by FillPavS** [comment]
Well, if the error is no longer there is no need to separate the function. Thx

**Comment by pops64** [comment]
Yea it probably was one of those internal hiccups that might have only need a game restart to sort out. I will close this out. If you have any future issues make sure you post them in the issues area. Thanks. Sorry if I came off harsh. CP is very complicated and long and we try to keep it has simple has possible

**Pull request closed without merging**
