### PR TITLE
added shovel positioning via keys

### PR DESCRIPTION
**Pull request by AndyK70**
**Input bindings are not predefined!**
Users see the input bindings ingame in the options for key bindings and have to set them on their own.
shovel positioning by keys works only if:
1. engine is running
2. player is driving the vehicle himself
3. the actual vehicle has a shovel attached :roll_eyes:

The work mode (cp.mode) is not altered. So if the player has set mode 2 or 4, then hired a worker, interrupted the worker to shovel some stuff and after that hit the keybinding to hire the worker again without looking at the work mode the hired worker will work (again) on that work mode the player has set before.

Translators, please check if translations for **input_COURSEPLAY_SHOVEL_MOVE_TO_*** have to be corrected.

### CODE REVIEW

**Comment by AndyK70** [comment]
I wasn't aware of setCpVar and when I had a glimpse at the function definition of setCourseplayFunc I saw that when the first argument begins with "self" or with "courseplay" it will set those variables. So I used it without looking out for another function which could take the task.
But I can change it to setCpVar, or you can, if you like so.
There's no reason not to use the designated function.

**Comment by AndyK70** [comment]
Is there anything more I have to do, or just let it sit here until you decide to merge it or not?

Have a nice WE and happy farming. :smile:

**Comment by AndyK70** [comment]
yes it can be removed without any problems.
I had it commented out when I was testing it and then just forgot to remove the leftovers. :blush:

**Comment by jhomer** [comment]
I always looked for this feature to be added over the last couple years. I don't think it's been added yet but I tried and added the code myself to try it out but for some reason I could not get it to work. Guessing I made some sort of mistake, or is this not workable for some reason? I could assign the input bindings pre-game but nothing would happen after, in-game.

**Comment by pops64** [comment]
When messing with input bindings you have to sometimes delta your current Bindings.xml for it to register

**Comment by jhomer** [comment]
You must be right @pops64  or I did something wrong when adding the code in. I can set the input bindings after the game loads in the options menu, I did not change the xml itself. Then in the game I save the bucket positions but I'm not able to "move to position" with the input bindings, only in the courseplay hud with the mouse. Otherwise I'll just wait until you guys add it to a version and try again at that time.

**Comment by AndyK70** [comment]
Did you set all 4 positions or just some?
Did you save your game after setting the positions and tested it again after restarting your savegame?

**Comment by AndyK70** [comment]
Ah, I think I found the issue but it's not in the code :relaxed:

In the keyboard settings you have to assign a single key as you do for all CP related keys.
Like showing or hiding the HUD it's only the key DEL. Hire or fire a CP worker is only KP_7 
But (!!) when you are ingame playing you always have to use the modifier key to use these and for the shovel positions it's the same. In the settings you only set a single key but ingame you have to use the CP-modifier + the key.

**Comment by jhomer** [comment]
@AndyK70 I did not mean to say it was an issue with your code, I thought I just made a mistake when adding your code to the current CP files.

Yes, you are correct. I was not using the modifier key. I added your code to the most recent CP and it works as it should. I don't know much about lua's but after you mention the modifier key, I can now see that. It works with keys and I use an xbox 360 controller and it works with that as well. There just isn't enough buttons on the 360 controller

Thanks!

**Comment by pvajko** [comment]
Sorry, I lost track, what is the status of this? Is any action item left or is it ready to be merged?

**Comment by AndyK70** [comment]
I think this evening I may have the time to remove all the commented out debug code as requested by you on 5th of July.

**Pull request merged**
