### PR TITLE
Optimizing course generation

### PR DESCRIPTION
**Pull request by AndyK70**
I tested this optimization a lot, with combine, drivers with tippers, loading wagons, tractors with sowing, fertilizer, mowing, swathing. Didn't find showstoppers.
I reduced the default optimizing to 5 (instead of 10 which I was testing and still using), to be on safe side even on hilly maps which are more hilly than Westbridge Hills.

The optimization factor can be adjusted in the courseplay.xml
the tag courseGeneration is added to the xml with two parameters.

First is maxPointsAtTurn, which default is set to 5. This value describes the waypoints right before and after a turn, which will stay as they are and won't be optimized. This helps the vehicle to get on line again after a turn smaller then the turn diameter. If maxPointsAtTurn are to low, the vehicle will go longer way off line before staying on. Seems the vehicle interpolates the waypoints when getting on line again. If you use the grimme trailer with 3m turns you may set maxPointsAtTurn even higher.

Second is stepForPoints which default is set to 5. This means every 5th waypoint will stay and the other 4 waypoints will be removed.
If you set it to somewhat like 10 then 9 will be removed and the 10th will stay.
My consideration for stepForPoints is a setting between 2 and 10. 2 is very low and 10 is good, but I won't go further. Maybe on 4x maps with large and even fields, but not on very hilly maps.

### CODE REVIEW

**Comment by ThomasGaertner** [comment]
I'm a bit confused: you asked us to implement it, we said "no" after thinking about it.
you asked a second time, we said no again. in a other forum you confirmed it that we denied it.
so why now this pull request ? do you think, we are not able or too lazy to do it ?
don't get me wrong, in general its a good idea and we appreciate your work. but unfortunately we have to think of all users and not only the 10% who are able to change values in the xml. especially you should know, what happens on the forums , if we implement things , which are not working properly.
I can not read any comments like " autocombine can get around the fruit, why can't  Cp " or "they  have definately the wrong approach and they will never get it " any more. Be sure we have  more ideas on our hard discs concerning every known problem than you can imagine. but they are all not suitable for the common user and that's our main problem. we need guys like you with new ideas and the knowledge to  define the issues to  solve it , but please understand us that we can not satisfy all wishes we and you have. Thanks

**Comment by AndyK70** [comment]
ok, i accept it
It's just the "not working properly" thing I don't get and why I was changing my approach, then testing and tweaking a lot.
I've haven't found a situation where it does not work, that's why I proposed this again. I'm working with this optimization every day and with higher (therefor more risky) optimization settings and all goes well.
You were talking about the common user, who won't change settings in the xml. Well, no one has to, unless he/she would like to tweak the settings to optimize/reduce waypoints more than the default setting.
And that user will surely ask for "how to do it". That's why I implemented the setting in the xml, for easier editing and not to have to edit in the mod source code itself. A pointing to the xml and that tag, editing with a normal text-editor and it will be done.

Maybe I'm missing anything else, I would like to know what problems could arise I don't see. 
keeping in mind, the common user doesn't have to edit or tweak anything in config file.

**Comment by ThomasGaertner** [comment]
ok lets imagine, we've pulled it and you are sure, as you said, that there is no situation, where it doesn't work. I bet, it wouldn't take 24 hours that you would get this issue: 
"just loaded the last version and the sprayer leaves parts of the field "unsprayed" ". If you are lucky, you will get a pic of it, but mostly not. here is the pic
screenshot 2015-03-21 08 23 58
this is not to blame you, its just to show you how hard it is to think of all situations before pushing.

**Comment by AndyK70** [comment]
Interesting, how did you manage it?
Did you press B while it was driving?
Or is it artificial and you sprayed two separate times?

With unload/refill courses there are no problems with the backup.
I have large fields and the sprayer or sower had to refill and to come back. Same with foraging/pickup grass and straw. You already have a backup of 10 waypoints for normal courses. I reduced this accordingly to the optimization factor, not to have to go back so much more, but enough to have a reasonable backup.The backup is reduced only, on generated lines, not recorded ones.

**Comment by ThomasGaertner** [comment]
you reduced in mode 6 only, if you do so in mode4 like I did to prevent that the tractor will align several 100 meters (10 optimized waypoints) before the restart point, you will have this result. you could restart one point earlier but believe me, there will be guys who are complaining, as soon as the sprayer will start spraying 5 meters before the restart point.

**Comment by AndyK70** [comment]
bummer :D 
mode 4, ok, inserted the same if condition like in mode 6. (not commited right now)

> there will be guys who are complaining, as soon as the sprayer will start spraying 5 meters before the restart point.

Well, yes as there are always users complaining. Like you said, they complain that cp doesn't work as "perfect" as AutoCombine, well it's because they don't understand the principles. AutoCombine doesn't generate courses, but only looks some meters in front where the fruit edge is and it is far away from being perfect. Sometimes it let islands of fruit stay on field because of the irregular field edges with fields which have a narrow somwhere along. Like it happened to me with field 17 Bjornholm, depending on how big the workwidth is and from where you begin. 
I would answer: Depending on the waypoint system it is not possible to have the exact position of restart work. But what is better? Having some meters double fertilizer, or having some meters no fertilizer at all. Seed isn't used double, because it doesn't use if it is already seeded.

Here we are at the developer stage, why not testing it with users who are aware of this?
I would like to help and to put this further.

**Comment by ThomasGaertner** [comment]
we need to discuss it in our team. at the moment we are very busy with our jobs  in real live and other obligations, so it will take a while....

**Pull request closed without merging**
