### PR TITLE
Pull request for #3421

### PR DESCRIPTION
**Pull request by GeorgeEarslight**
Avoid using generateTurnTypeWideTurnWithAvoidance if the total vehicle length is greater than the 90 degrees turn radii it would generate.

### CODE REVIEW

**Comment by GeorgeEarslight** [comment]
No problem, had some time and decided to dig into it a bit.
The issue in 3421 was the final 90-90 turns, whose radii were lesser than the total length, so the tractor went looping around trying to reach the end of the circle segment.

image

Isn't deltaX the horizontal lane to lane distance?  I'm not sure, but if so it's irrelevant to the specific case.

**Comment by pvaiko** [comment]
No, it's not irrelevant. The problem is that those 90 turns are not generated correctly in the first place, probably because the original author assumed that the field is square. 

The end of the first 90 should line up with the beginning of the second (the one on the left in your picture) and there shouldn't be any straight section between the two.

**Comment by GeorgeEarslight** [comment]
Got it, I kind of understand what you mean now.
What is this supposed to do?
--- Generate line between second and third turn circles
I could try to dig more tomorrow.

**Comment by pvaiko** [comment]
I think it is trying to generate something like this (to avoid a concave corner which would be here in the bottom left part):

image

**Comment by GeorgeEarslight** [comment]
Thanks for the diagram, that's what I assumed after you said the quarter circles should be continuous. I didn't understand why CP needs to draw lines, hence
'--- Generate line between second and third turn circles' 
Since you already have the first quarter last way point and the second quarter start way point.

**Comment by GeorgeEarslight** [comment]
Have a possible fix for this, will push later.

**Pull request closed without merging**
