### PR TITLE
Update CombineUnloadAIDriver.lua

### PR DESCRIPTION
**Pull request by FarmerMoe**
To make room for tractor to turn without running into combine when trailer is full

### CODE REVIEW

**Comment by pvaiko** [comment]
Have you tested this?

**Comment by Tensuko** [comment]
Where do you set the position to unload ?
Where is the Pipe position of the Auger Wagons saved ?

**Comment by schwiti6190** [comment]
Might be better to create a new AIDriver that derives from CombineUnloadAIDriver for auger wagons mode. I might have a better solution for the unloading, will take a look at it .

**Comment by Tensuko** [comment]
That will be our mode3 like it always was, with pipepositions and defined unload as the drivwr does not drive thrue a trigger.

**Comment by pvaiko** [comment]
@schwiti6190 exactly, this needs to be a derived class of the CombineUnloadAIDriver, only need to to implement the unload course driving part, stopping at a wait point, wait for a trailer, open pipe. Should be pretty straightforward.

**Comment by FarmerMoe** [comment]
> Where do you set the position to unload ? 
I simply created an unload stop/trigger as part of the unload course. The unload stop point should be next to the mother bin/trailer that the chaser wagon unloads to when the pipe is open. 

> Where is the Pipe position of the Auger Wagons saved ? 
I did not store the pipe position. As a result, when the pipe is open at the start of the course, it will remain open until the wagon is unloaded and the pipe is closed by CP.

**Comment by FarmerMoe** [comment]
> Have you tested this?

I am using this in my game play to allow for unloading while the combine is moving. So far it has successfully prevented the chaser wagon from running into the combine as it starts on the path to drive towards the unload path.

**Comment by Tensuko** [comment]
> > Have you tested this?
> 
> I am using this in my game play to allow for unloading while the combine is moving. So far it has successfully prevented the chaser wagon from running into the combine as it starts on the path to drive towards the unload path.

So, it only does this:
If it gets full, it pulls back before drive to unload course ?

**Comment by FarmerMoe** [comment]
Yes, the changes I added yesterday simply pulls back when the wagon is full before switching to drive to upload course thereby avoiding the combine that unloaded while in motion.

**Pull request closed without merging**
