### PR TITLE
HUD text change

### PR DESCRIPTION
**Pull request by zed636**
same line same text in all translation

### CODE REVIEW

**Comment by pops64** [comment]
Instead of makeing 19 pushhes for each file. please edit all files and make one push with all your changes

**Comment by zed636** [comment]
I try, but I can't understand how to do it...sorry!

**Comment by pops64** [comment]
You edit all the files you want to change on a single branch then make a pull request here so we can review the changes before merging the branch

**Comment by zed636** [comment]
add new pull #2305

**Pull request closed without merging**
